/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLLChiTietMuonTra;
import BLL.BLLNhanVien;
import BLL.BLLSach;
import DAL.PrintMuonTra;
import DTO.ChiTietMuonTra;
import DTO.DocGia;
import DTO.MuonTra;
import DTO.NhanVien;
import DTO.Sach;
import static GUI.XemChiTietMuonSach.dsChiTiet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Hoang Giang
 */
public class CapNhatSachTrongDanhSachSachMuon extends javax.swing.JFrame {

    /**
     * Creates new form CapNhatSachTrongDanhSachSachMuon
     */
    static ArrayList<Sach> dsSach;
    static ArrayList<ChiTietMuonTra> dsChiTiet;
    BLLSach bllSach;
    SimpleDateFormat sdf;
    DefaultTableModel dtmTimKiemSach;
    DefaultTableModel dtm;
    BLLChiTietMuonTra bllChiTiet;
    ArrayList<ChiTietMuonTra> dsChiTietDaCo;
    ArrayList<String> sachBiThayDoi;
    ArrayList<String> dsngayTraTheoSach;
    BLLNhanVien bllNhanVien;

    public CapNhatSachTrongDanhSachSachMuon() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
        bllNhanVien = new BLLNhanVien();
        sachBiThayDoi = new ArrayList<String>();
        bllChiTiet = new BLLChiTietMuonTra();
        dsSach = new ArrayList<>();
        dsChiTiet = new ArrayList<>();
        bllSach = new BLLSach();
        dsngayTraTheoSach = new ArrayList<String>();
        sdf = new SimpleDateFormat("dd/MM/yyyy");
        DefaultComboBoxModel<String> itemComboxTimKiemTinhTrang = new DefaultComboBoxModel<String>();
        itemComboxTimKiemTinhTrang.addElement("Còn sách");
        itemComboxTimKiemTinhTrang.addElement("Đã cho mượn");
        itemComboxTimKiemTinhTrang.addElement("Không tồn tại");
        dtm = new DefaultTableModel();
        dtm.addColumn("Mã Sách");
        dtm.addColumn("Tên Sách");
        dtm.addColumn("Tác Giả");
        dtm.addColumn("Nhà Xuất Bản");
        dtm.addColumn("Thể Loại");
        dtm.addColumn("Ngày Trả");
        dtm.addColumn("Tiền Phạt");
        cbxTinhTrang.setModel(itemComboxTimKiemTinhTrang);
        cbxTinhTrang.setSelectedIndex(-1);
        hienThiDanhSachSachMuon();
        hienThiToanBoSach();
        lblMaMuonTra.setText(QuanLyMuonTra.mtChon.getMaMuonTra());
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
    }

    private void hienThiToanBoSach() {

    }

    private void hienThiDanhSachSachMuon() {
        dsChiTiet.clear();
        dsChiTiet = bllChiTiet.timChiTietMuonTra(QuanLyMuonTra.mtChon.getMaMuonTra());
        dsChiTietDaCo = bllChiTiet.timChiTietMuonTra(QuanLyMuonTra.mtChon.getMaMuonTra());
        for (ChiTietMuonTra c : dsChiTietDaCo) {
            if (c.getNgayTra() == null) {
                dsngayTraTheoSach.add("");
            } else {
                dsngayTraTheoSach.add(sdf.format(c.getNgayTra()));
            }
        }
        dsSach.clear();
        for (ChiTietMuonTra ct : dsChiTiet) {
            Sach s = bllSach.timSachTheoMa(ct.getMaSach());
            dsSach.add(s);
        }
        for (int i = 0; i < dsChiTiet.size(); i++) {
            Vector<String> v = new Vector<>();
            Sach sach = dsSach.get(i);
            v.add(sach.getMaSach_20151094());
            v.add(sach.getTenSach_20151094());
            v.add(sach.getTacGia_20151094());
            v.add(sach.getNhaXuatBan_20151094());
            v.add(sach.getTheLoai_20151094());
            ChiTietMuonTra ct = dsChiTiet.get(i);
            if (ct.getNgayTra() != null) {
                v.add(sdf.format(ct.getNgayTra()));
            } else {
                v.add("");
            }
            v.add(ct.getTienPhat() + "");
            dtm.addRow(v);
        }
        tblDanhSachSachMuon.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserNgayTra = new com.toedter.calendar.JDateChooser();
        txtTheLoai = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        lblMaMuonTra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNhaXuatBan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxTinhTrang = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtTienPhat = new javax.swing.JTextField();
        btnTimSach = new javax.swing.JButton();
        btnThemSach = new javax.swing.JButton();
        btnXoaSach = new javax.swing.JButton();
        btnXemToabBo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKetQua = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSachSachMuon = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        chkInThongTin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh1.png"))); // NOI18N
        jLabel1.setText("Cập Nhật Sách Trong Danh Sách Sách Mượn");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("@Author Nguyễn Hoàng Giang");

        jLabel12.setText("MSSV: 20151094");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Mã Sách:");

        jLabel6.setText("Tác Giả:");

        jLabel8.setText("Thể Loại:");

        jLabel3.setText("Ngày Trả:");

        jDateChooserNgayTra.setDateFormatString("dd/MM/yyyy");

        lblMaMuonTra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaMuonTra.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã Mượn Trả:");

        jLabel5.setText("Tên Sách:");

        jLabel7.setText("Nhà Xuất Bản:");

        jLabel9.setText("Tình Trạng");

        jLabel10.setText("Tiền Phạt:");

        txtTienPhat.setEditable(false);

        btnTimSach.setBackground(new java.awt.Color(51, 204, 255));
        btnTimSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Search-16.png"))); // NOI18N
        btnTimSach.setText("Tìm Kiếm Sách");
        btnTimSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSachActionPerformed(evt);
            }
        });

        btnThemSach.setBackground(new java.awt.Color(51, 204, 255));
        btnThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Add-16.png"))); // NOI18N
        btnThemSach.setText("Thêm Sách");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        btnXoaSach.setBackground(new java.awt.Color(51, 204, 255));
        btnXoaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Delete-16a.png"))); // NOI18N
        btnXoaSach.setText("Xóa Sách");
        btnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachActionPerformed(evt);
            }
        });

        btnXemToabBo.setBackground(new java.awt.Color(51, 204, 255));
        btnXemToabBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-select-all.png"))); // NOI18N
        btnXemToabBo.setText("Xem Toàn Bộ Sách Còn");
        btnXemToabBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemToabBoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết Quả Tìm Kiếm:"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tblKetQua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Nhà Xuất Bản", "Thể Loại", "Tình Trạng"
            }
        ));
        jScrollPane1.setViewportView(tblKetQua);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Sách Mượn"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        tblDanhSachSachMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Nhà Xuất Bản", "Thể Loại", "Ngày Trả", "Tiền Phạt"
            }
        ));
        tblDanhSachSachMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDanhSachSachMuonMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSachSachMuon);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/success.png"))); // NOI18N
        jButton4.setText("Xong");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 204, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Cancel-16.png"))); // NOI18N
        jButton5.setText("Hủy Bỏ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Edit-16a.png"))); // NOI18N
        jButton1.setText("Trả Sách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkInThongTin.setBackground(new java.awt.Color(51, 204, 255));
        chkInThongTin.setText("In Thông Tin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserNgayTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(24, 24, 24)
                                        .addComponent(txtTienPhat)))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnXemToabBo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnXoaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThemSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTimSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaMuonTra, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(chkInThongTin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMaMuonTra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTheLoai, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbxTinhTrang, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.CENTER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooserNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXemToabBo)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(chkInThongTin))
                            .addComponent(jButton5))
                        .addGap(25, 25, 25))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btnXoaSach)
                .addContainerGap(446, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSachActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();
        String tacGia = txtTacGia.getText();
        String nhaXuatBan = txtNhaXuatBan.getText();
        String theLoai = txtTheLoai.getText();
        if (maSach.equals("") && tenSach.equals("") && tacGia.equals("") && nhaXuatBan.equals("") && theLoai.equals("") && cbxTinhTrang.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            return;
        } else {
            if (cbxTinhTrang.getSelectedIndex() == -1) {
                String tinhTrang = "";
                ArrayList<Sach> ds = bllSach.timKiemSach("%" + maSach + "%", "%" + tenSach + "%", "%" + tacGia + "%", "%" + nhaXuatBan + "%", "%" + theLoai + "%", "%" + tinhTrang + "%");
                dtmTimKiemSach = addDuLieuChotblTimKiem(ds);

                tblKetQua.setModel(dtmTimKiemSach);
            } else {
                String tinhTrang = cbxTinhTrang.getSelectedItem().toString();
                ArrayList<Sach> ds = bllSach.timKiemSach("%" + maSach + "%", "%" + tenSach + "%", "%" + tacGia + "%", "%" + nhaXuatBan + "%", "%" + theLoai + "%", "%" + tinhTrang + "%");
                dtmTimKiemSach = addDuLieuChotblTimKiem(ds);
                tblKetQua.setModel(dtmTimKiemSach);
            }
        }
    }//GEN-LAST:event_btnTimSachActionPerformed

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        // TODO add your handling code here:
        int[] row = tblKetQua.getSelectedRows();
        if (row.length <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sách muốn thêm vào");
        } else {
            for (int i : row) {
                Sach sach = new Sach();
                sach.setMaSach_20151094(tblKetQua.getValueAt(i, 0) + "");
                sach.setTenSach_20151094(tblKetQua.getValueAt(i, 1) + "");
                sach.setTacGia_20151094(tblKetQua.getValueAt(i, 2) + "");
                sach.setNhaXuatBan_20151094(tblKetQua.getValueAt(i, 3) + "");
                sach.setTheLoai_20151094(tblKetQua.getValueAt(i, 4) + "");
                dsSach.add(sach);
                ChiTietMuonTra ct = new ChiTietMuonTra();
                ct.setMaMuonTra(lblMaMuonTra.getText());
                ct.setMaSach(sach.getMaSach_20151094());
                ct.setNgayTra(null);
                ct.setTienPhat(0);
                dsChiTiet.add(ct);
                Vector<String> v = new Vector<>();
                v.add(sach.getMaSach_20151094());
                v.add(sach.getTenSach_20151094());
                v.add(sach.getTacGia_20151094());
                v.add(sach.getNhaXuatBan_20151094());
                v.add(sach.getTheLoai_20151094());
                if (ct.getNgayTra() != null) {
                    v.add(sdf.format(ct.getNgayTra()));
                } else {
                    v.add("");
                }
                v.add(ct.getTienPhat() + "");
            }
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Mã Sách");
            dtm.addColumn("Tên Sách");
            dtm.addColumn("Tác Giả");
            dtm.addColumn("Nhà Xuất Bản");
            dtm.addColumn("Thể Loại");
            dtm.addColumn("Ngày Trả");
            dtm.addColumn("Tiền Phạt");
            int bd = 0;
            while (bd < dsSach.size()) {
                Sach s = dsSach.get(bd);
                Vector<String> v = new Vector<>();
                v.add(s.getMaSach_20151094());
                v.add(s.getTenSach_20151094());
                v.add(s.getTacGia_20151094());
                v.add(s.getNhaXuatBan_20151094());
                v.add(s.getTheLoai_20151094());
                ChiTietMuonTra ct = dsChiTiet.get(bd);
                if (ct.getNgayTra() == null) {
                    v.add("");
                } else {
                    v.add(sdf.format(ct.getNgayTra()));
                }
                v.add(ct.getTienPhat() + "");
                dtm.addRow(v);
                bd++;
            }
            tblDanhSachSachMuon.setModel(dtm);
        }
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachActionPerformed
        // TODO add your handling code here:
        int[] row = tblDanhSachSachMuon.getSelectedRows();
        if (row.length <= 0) {
            JOptionPane.showMessageDialog(null, "Chưa chọn sách ở rỏ muốn xóa");
        } else {
            for (int i = row.length - 1; i >= 0; i--) {
                String maSachXoa = tblDanhSachSachMuon.getValueAt(row[i], 0) + "";
                if (!kiemTraChiTietTonTaiTrongRo(lblMaMuonTra.getText(), maSachXoa)) {
                    dsSach.remove(row[i]);
                    dsChiTiet.remove(row[i]);
                } else {
                    String strTenSach = tblDanhSachSachMuon.getValueAt(row[i], 1) + "";
                    String strNgayTra = tblDanhSachSachMuon.getValueAt(row[i], 5) + "";
                    if (strNgayTra.matches("\\s*")) {
                        JOptionPane.showMessageDialog(null, "<html><p>Sách (" + maSachXoa + ") " + strTenSach.trim() + " chưa được trả.</p>"
                                + "<p>Vui lòng trả sách trước");
                    } else {
                        int xacNhan = JOptionPane.showConfirmDialog(null, "<html><p>Sách " + tblDanhSachSachMuon.getValueAt(row[i], 1) + " đã được trả</p>"
                                + "<p>Nếu bạn xóa thì sẽ không thể khôi phục</p>"
                                + "<p>Bạn có chắc chắn muốn xóa ?</p>"
                                + "</html>", "Xác nhận", JOptionPane.YES_NO_OPTION);
                        if (xacNhan == JOptionPane.YES_OPTION) {
                            dsSach.remove(row[i]);
                            dsChiTiet.remove(row[i]);
                        }
                    }

                }
            }
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Mã Sách");
            dtm.addColumn("Tên Sách");
            dtm.addColumn("Tác Giả");
            dtm.addColumn("Nhà Xuất Bản");
            dtm.addColumn("Thể Loại");
            dtm.addColumn("Ngày Trả");
            dtm.addColumn("Tiền Phạt");
            int bd = 0;
            while (bd < dsSach.size()) {
                Sach s = dsSach.get(bd);
                Vector<String> v = new Vector<>();
                v.add(s.getMaSach_20151094());
                v.add(s.getTenSach_20151094());
                v.add(s.getTacGia_20151094());
                v.add(s.getNhaXuatBan_20151094());
                v.add(s.getTheLoai_20151094());
                ChiTietMuonTra ct = dsChiTiet.get(bd);
                if (ct.getNgayTra() == null) {
                    v.add("");
                } else {
                    v.add(sdf.format(ct.getNgayTra()));
                }
                v.add(ct.getTienPhat() + "");
                dtm.addRow(v);
                bd++;
            }
            tblDanhSachSachMuon.setModel(dtm);
        }
    }//GEN-LAST:event_btnXoaSachActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int kiemTra = JOptionPane.showConfirmDialog(null, "Bạn có muốn kết thúc cập nhật", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (kiemTra == JOptionPane.YES_OPTION) {
            System.out.println("Danh sách ới" + dsSach.size());
            System.out.println("Danh sách cũ" + XemChiTietMuonSach.dsSach.size());
            for (ChiTietMuonTra c : dsChiTiet) {
                System.out.println(c.getMaMuonTra() + " " + c.getMaSach() + " " + c.getNgayTra() + c.getTienPhat());
            }
            for (ChiTietMuonTra c : dsChiTiet) {
                String maS = c.getMaSach();
                if (sachBiThayDoi.contains(maS)) {
                    bllChiTiet.suaChiTietMuonTra(lblMaMuonTra.getText(), maS, c.getNgayTra() != null ? sdf.format(c.getNgayTra()) : "", c.getTienPhat() + "");
                    bllSach.suaTinhTrangSach(maS, "Còn Sách");
                }
            }
            System.out.println("Dữ liệu cũ có " + dsChiTietDaCo.size());
            System.out.println("Dữ liệu mới có " + dsChiTiet.size());
            int xoa = 0;
            int them = 0;
            for (ChiTietMuonTra chitiet : dsChiTietDaCo) {
                if (!dsChiTiet.contains(chitiet)) {
                    bllChiTiet.xoaChiTietMuonTra(chitiet.getMaMuonTra(), chitiet.getMaSach());
                    System.out.println("Xóa " + chitiet.getMaMuonTra() + " " + chitiet.getMaSach());
                    bllSach.suaTinhTrangSach(chitiet.getMaSach(), "Còn Sách");
                    xoa++;
                }

            }
            System.out.println("Xóa " + xoa);
            for (ChiTietMuonTra chitiet : dsChiTiet) {
                if (!dsChiTietDaCo.contains(chitiet)) {
                    bllChiTiet.themChiTietMuonTra(chitiet.getMaMuonTra(), chitiet.getMaSach(), "null", "0");
                    bllSach.suaTinhTrangSach(chitiet.getMaSach(), "Đã Cho Mượn");
                    them++;
                    System.out.println("Thêm " + chitiet.getMaMuonTra() + " " + chitiet.getMaSach());
                }
            }
            
            System.out.println("Thêm " + them);
            if (chkInThongTin.isSelected() == true) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                this.dispose();
                hienThiGiaoDienIn();
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void hienThiGiaoDienIn() {
        ArrayList<ChiTietMuonTra> ds = bllChiTiet.timChiTietMuonTra(QuanLyMuonTra.mtChon.getMaMuonTra());
        int tienPhat = 0;
        for (ChiTietMuonTra ct : ds) {
            tienPhat += ct.getTienPhat();
        }
        MuonTra mt = new MuonTra();
        NhanVien nv = new NhanVien();
        DocGia dg = new DocGia();
        if (XemChiTietMuonSach.mt != null) {
            mt = XemChiTietMuonSach.mt;
        }
        if (XemChiTietMuonSach.nv != null) {
            nv = XemChiTietMuonSach.nv;
        }
        if (XemChiTietMuonSach.dg != null) {
            dg = XemChiTietMuonSach.dg;
        }
        System.out.println("Mã mượn trả" + QuanLyMuonTra.mtChon.getMaMuonTra());
        System.out.println("Tiền phạt:" + tienPhat);
        PrintMuonTra.printMuonSach(mt, nv, dg, tienPhat + "");
    }
    private void tblDanhSachSachMuonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSachMuonMousePressed
        // TODO add your handling code here:
        int row = tblDanhSachSachMuon.getSelectedRow();
        txtMaSach.setText(tblDanhSachSachMuon.getValueAt(row, 0) + "");
        txtTenSach.setText(tblDanhSachSachMuon.getValueAt(row, 1) + "");
        txtTacGia.setText(tblDanhSachSachMuon.getValueAt(row, 2) + "");
        txtNhaXuatBan.setText(tblDanhSachSachMuon.getValueAt(row, 3) + "");
        txtTheLoai.setText(tblDanhSachSachMuon.getValueAt(row, 4) + "");
        String ngayTra = tblDanhSachSachMuon.getValueAt(row, 5) + "";
        Date ngayTraDate = null;
        if (!ngayTra.equals("")) {
            try {
                ngayTraDate = sdf.parse(ngayTra);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        jDateChooserNgayTra.setDate(ngayTraDate);
        txtTienPhat.setText(tblDanhSachSachMuon.getValueAt(row, 6) + "");

    }//GEN-LAST:event_tblDanhSachSachMuonMousePressed

    private void btnXemToabBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemToabBoActionPerformed
        // TODO add your handling code here:
        ArrayList<Sach> ds = bllSach.timKiemSach("%%", "%%", "%%", "%%", "%%", "%Còn Sách%");
        dtmTimKiemSach = addDuLieuChotblTimKiem(ds);
        tblKetQua.setModel(dtmTimKiemSach);
    }//GEN-LAST:event_btnXemToabBoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = tblDanhSachSachMuon.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một sách cần cập nhật");
            return;
        }
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn trả quyển sách này", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            if (kiemTraChiTietTonTaiTrongRo(lblMaMuonTra.getText(), txtMaSach.getText())) {
                String strNgayTra1 = tblDanhSachSachMuon.getValueAt(row, 5) + "";
                if (!strNgayTra1.matches("\\s*")) {
                    JOptionPane.showMessageDialog(null, "Sách đã được trả trước đó");
                    return;
                }
                Calendar cal = Calendar.getInstance();
                Date ngayTra = cal.getTime();
                jDateChooserNgayTra.setDate(ngayTra);
                int tienPhat = (int) tinhTienPhat(QuanLyMuonTra.mtChon.getNgayHenTra());
                txtTienPhat.setText(tienPhat + "");
                tblDanhSachSachMuon.setValueAt(sdf.format(ngayTra), row, 5);
                tblDanhSachSachMuon.setValueAt(tienPhat, row, 6);
                String maSach = tblDanhSachSachMuon.getValueAt(row, 0) + "";
                sachBiThayDoi.add(maSach);
                for (ChiTietMuonTra c : dsChiTiet) {
                    if (c.getMaSach().equals(maSach)) {
                        c.setNgayTra(jDateChooserNgayTra.getDate());
                        try {
                            c.setTienPhat(Integer.parseInt(txtTienPhat.getText()));
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Sách này chưa được đăng ký mượn nên không trả được");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private long tinhTienPhat(Date ngayHenTra) {
        Calendar cal = Calendar.getInstance();
        Date ngayTra = cal.getTime();
        long diff = ngayTra.getTime() - ngayHenTra.getTime();
        long soNgay = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
        System.out.println("số ngày trả muộn:" + soNgay);
        return soNgay * 1000;
    }

    private boolean kiemTraChiTietTonTaiTrongRo(String maMuonTra, String maSach) {
        ChiTietMuonTra ct = new ChiTietMuonTra();
        ct.setMaMuonTra(maMuonTra);
        ct.setMaSach(maSach);
        if (dsChiTietDaCo.contains(ct)) {
            return true;
        }
        return false;
    }

    private boolean kiemTraChiTietTonTaiTrongRo(String maMuonTra, String maSach, String ngayTra) {
        ChiTietMuonTra ct = new ChiTietMuonTra();
        ct.setMaMuonTra(maMuonTra);
        ct.setMaSach(maSach);
        if (ngayTra.matches("\\s*")) {
            ct.setNgayTra(null);
        } else {
            try {
                ct.setNgayTra(sdf.parse(ngayTra));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        if (dsChiTietDaCo.contains(ct)) {
            return true;
        }
        return false;
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int kq = JOptionPane.showConfirmDialog(null, "Bạn muốn hủy bỏ những gì đã làm lúc nãy", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private DefaultTableModel addDuLieuChotblTimKiem(ArrayList<Sach> ds) {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã Sách");
        dtm.addColumn("Tên Sách");
        dtm.addColumn("Tác Giả");
        dtm.addColumn("Nhà Xuất Bản");
        dtm.addColumn("Thể Loại");
        dtm.addColumn("Tình Trạng");
        for (Sach s : ds) {
            Vector<String> v = new Vector<>();
            v.add(s.getMaSach_20151094());
            v.add(s.getTenSach_20151094());
            v.add(s.getTacGia_20151094());
            v.add(s.getNhaXuatBan_20151094());
            v.add(s.getTheLoai_20151094());
            v.add(s.getTinhTrang_20151094());
            dtm.addRow(v);
        }
        return dtm;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatSachTrongDanhSachSachMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatSachTrongDanhSachSachMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatSachTrongDanhSachSachMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatSachTrongDanhSachSachMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatSachTrongDanhSachSachMuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnTimSach;
    private javax.swing.JButton btnXemToabBo;
    private javax.swing.JButton btnXoaSach;
    private javax.swing.JComboBox<String> cbxTinhTrang;
    private javax.swing.JCheckBox chkInThongTin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooserNgayTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaMuonTra;
    private javax.swing.JTable tblDanhSachSachMuon;
    private javax.swing.JTable tblKetQua;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNhaXuatBan;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTheLoai;
    private javax.swing.JTextField txtTienPhat;
    // End of variables declaration//GEN-END:variables
}
