/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.TaiKhoan;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Nguyen Hoang Giang
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    SimpleDateFormat sdfgio;

    public Menu() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
//        this.setTitle("Xin chào " + DataBaseQuery.layTenNhanVienTuTenDangNhap(con, JFloginV2.txtTenDangNhap.getText()));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        Calendar cal = Calendar.getInstance();
        Date ngay = cal.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
        lblNgayThang.setText("Hà Nội,Thứ " + cal.get(Calendar.DAY_OF_WEEK) + " Ngày " + cal.get(Calendar.DAY_OF_MONTH) + " Tháng " + cal.get(Calendar.MONTH) + " Năm " + cal.get(Calendar.YEAR));
        sdfgio = new SimpleDateFormat("hh:mm:ss aa");
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar cal = Calendar.getInstance();
                Date ngay = cal.getTime();
                lblGio.setText(sdfgio.format(ngay));
            }
        });
        timer.start();
        autoDoiMauChu(jLabel2, Color.BLACK, Color.cyan);
        autoDoiMauChu(jLabel3, Color.BLACK, Color.RED);
        autoDoiMauChu(jLabel4, Color.RED, Color.GREEN);
        autoDoiMauChu(lblNgayThang, Color.BLACK, Color.RED);
//        this.pack();
        JFrame ui = this;
        ui.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                titleAlign(ui);
            }

        });
    }

    private void titleAlign(JFrame frame) {

        Font font = frame.getFont();

        String currentTitle = frame.getTitle().trim();
        FontMetrics fm = frame.getFontMetrics(font);
        int frameWidth = frame.getWidth();
        int titleWidth = fm.stringWidth(currentTitle);
        int spaceWidth = fm.stringWidth(" ");
        int centerPos = (frameWidth / 2) - (titleWidth / 2);
        int spaceCount = centerPos / spaceWidth;
        String pad = "";
        pad = String.format("%" + (spaceCount - 14) + "s", pad);
        frame.setTitle(pad + currentTitle);

    }

    private void autoDoiMauChu(JLabel lbl, Color col1, Color col2) {
        Timer t = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (lbl.getForeground() == col1) {
                    lbl.setForeground(col2);
                } else {
                    lbl.setForeground(col1);
                }
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNgayThang = new javax.swing.JLabel();
        lblGio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mnuChucNang = new javax.swing.JMenuBar();
        mnuQuanLySach = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuQuanLyNhanVien = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnuQuanLyDocGia = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        setTitle("Phầm Mềm Quản Lý Thư Viện");
        setBackground(new java.awt.Color(255, 255, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Library_100.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Trường Đại Học Bách Khoa Hà Nội");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Thư Viện Tạ Quang Bửu");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Nguyễn Hoàng Giang - 20151094");

        lblNgayThang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNgayThang.setText("Hà Nội, Ngày 16 tháng 10 năm 2017");

        lblGio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGio.setForeground(new java.awt.Color(0, 51, 255));
        lblGio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Xem Thông Tin Tài Khoản");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(37, 37, 37))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(lblNgayThang)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNgayThang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        mnuChucNang.setBackground(new java.awt.Color(255, 255, 0));
        mnuChucNang.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuChucNang.setPreferredSize(new java.awt.Dimension(493, 60));

        mnuQuanLySach.setBackground(new java.awt.Color(255, 255, 0));
        mnuQuanLySach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/windows.png"))); // NOI18N
        mnuQuanLySach.setText("Quản Lý");
        mnuQuanLySach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuQuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuQuanLySachMousePressed(evt);
            }
        });
        mnuQuanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuanLySachActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_books-64.png"))); // NOI18N
        jMenuItem1.setText("Quản Lý Sách");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuQuanLySach.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_icons8-user-96.png"))); // NOI18N
        jMenuItem2.setText("Quản Lý Nhân Viên");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuQuanLySach.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_354637.png"))); // NOI18N
        jMenuItem3.setText("Quản Lý Độc Giả");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuQuanLySach.add(jMenuItem3);

        mnuChucNang.add(mnuQuanLySach);

        mnuQuanLyNhanVien.setBackground(new java.awt.Color(255, 255, 0));
        mnuQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_owl-book-64.png"))); // NOI18N
        mnuQuanLyNhanVien.setText("Mượn Trả");
        mnuQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuQuanLyNhanVienMousePressed(evt);
            }
        });
        mnuQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuanLyNhanVienActionPerformed(evt);
            }
        });

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sign-up-16.png"))); // NOI18N
        jMenuItem4.setText("Đăng Ký Mượn Sách");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuQuanLyNhanVien.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open-book.png"))); // NOI18N
        jMenuItem5.setText("Quản Lý Mượn Sách");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuQuanLyNhanVien.add(jMenuItem5);

        mnuChucNang.add(mnuQuanLyNhanVien);

        mnuQuanLyDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/analytics.png"))); // NOI18N
        mnuQuanLyDocGia.setText("Thống Kê");
        mnuQuanLyDocGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuQuanLyDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuQuanLyDocGiaMousePressed(evt);
            }
        });
        mnuQuanLyDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuanLyDocGiaActionPerformed(evt);
            }
        });
        mnuChucNang.add(mnuQuanLyDocGia);

        mnuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        mnuDangXuat.setText("Đăng Xuất");
        mnuDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuDangXuatMousePressed(evt);
            }
        });
        mnuChucNang.add(mnuDangXuat);

        setJMenuBar(mnuChucNang);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuQuanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuanLySachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuQuanLySachActionPerformed

    private void mnuQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuQuanLyNhanVienActionPerformed

    private void mnuQuanLyDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuanLyDocGiaActionPerformed
        // TODO add your handling code here:
        ThongKe ui = new ThongKe();
    }//GEN-LAST:event_mnuQuanLyDocGiaActionPerformed

    private void mnuQuanLySachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuanLySachMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuQuanLySachMousePressed

    private void mnuQuanLyNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuanLyNhanVienMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuQuanLyNhanVienMousePressed

    private void mnuQuanLyDocGiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuanLyDocGiaMousePressed
        // TODO add your handling code here:
        ThongKe ui = new ThongKe();
        ui.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuQuanLyDocGiaMousePressed

    private void mnuDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDangXuatMousePressed
        // TODO add your handling code here:
        this.dispose();
        Login frame = new Login();
        frame.setVisible(true);
    }//GEN-LAST:event_mnuDangXuatMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        ThongTinTaiKhoan frame = new ThongTinTaiKhoan();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        QuanLySach ui = new QuanLySach();
        ui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        QuanLyNhanVien ui = new QuanLyNhanVien();
        ui.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        QuanLyDocGia ui = new QuanLyDocGia();
        ui.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        DangKyMuonSach ui = new DangKyMuonSach();
        ui.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        QuanLyMuonTra ui = new QuanLyMuonTra();
        ui.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNgayThang;
    private javax.swing.JMenuBar mnuChucNang;
    private javax.swing.JMenu mnuDangXuat;
    private javax.swing.JMenu mnuQuanLyDocGia;
    private javax.swing.JMenu mnuQuanLyNhanVien;
    private javax.swing.JMenu mnuQuanLySach;
    // End of variables declaration//GEN-END:variables
}
