/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.KiemTraDuLieuNhapThoaMan;
import DAL.ImportFileExcel;
import DAL.PrintSach;
import DTO.Sach;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Hoang Giang
 */
public class QuanLySach extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySach
     */
    BLL.BLLSach bllSach;
    DefaultTableModel dtmTimKiemSach;
    PrintSach printSach;
    DefaultTableModel dtmMau;
    ImportFileExcel importFile;
    SimpleDateFormat sdf;
    JButton btnLast;

    public QuanLySach() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        bllSach = new BLL.BLLSach();
        printSach = new PrintSach();
        importFile = new ImportFileExcel();
        dtmMau = new DefaultTableModel();
        dtmMau.addColumn("Mã Sách");
        dtmMau.addColumn("Tên Sách");
        dtmMau.addColumn("Tác Giả");
        dtmMau.addColumn("Nhà Xuất Bản");
        dtmMau.addColumn("Thể Loại");
        dtmMau.addColumn("Tình Trạng");
        DefaultComboBoxModel<String> itemComboxTimKiemTinhTrang = new DefaultComboBoxModel<String>();
        itemComboxTimKiemTinhTrang.addElement("Còn sách");
        itemComboxTimKiemTinhTrang.addElement("Đã cho mượn");
        itemComboxTimKiemTinhTrang.addElement("Không tồn tại");
        cbxTimKiemTinhTrang.setModel(itemComboxTimKiemTinhTrang);
        cbxTimKiemTinhTrang.setSelectedIndex(-1);
        tblTimKiemKetQua.setModel(dtmMau);
        hienThiToanBoSachLenBangDanhSach();
        autoDoiMauChu(jLabel1, Color.BLACK, Color.RED);
        Color col = jLabel7.getForeground();
        autoDoiMauChu(jLabel7, col, Color.GREEN);
        sdf = new SimpleDateFormat("hh:mm:ss aa");
        Color mauChu = jLabel10.getForeground();
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar cal = Calendar.getInstance();
                jLabel10.setText(sdf.format(cal.getTime()));
                if (jLabel10.getForeground() == mauChu) {
                    jLabel10.setForeground(Color.BLACK);
                } else {
                    jLabel10.setForeground(mauChu);
                }
            }
        });
        t.start();
        Calendar cal = Calendar.getInstance();
        jLabel10.setText(sdf.format(cal.getTime()));
        jScrollPane3.setOpaque(false);
        jScrollPane3.getViewport().setOpaque(false);
        if(!Login.txtTenDangNhap.getText().equalsIgnoreCase("admin")){
            gioiHanChucNang();
        }
    }
    
    private void gioiHanChucNang(){
        btnCapNhatThemSach.setEnabled(false);
        jButton1.setEnabled(false);
        btnCapNhatSuaSach.setEnabled(false);
        btnCapNhatXoaSach.setEnabled(false);
    }
    
    private void autoDoiMauChu(JLabel lbl, Color col1, Color col2) {
        Timer t = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (lbl.getForeground() == col1) {
                    lbl.setForeground(col2);
                } else {
                    lbl.setForeground(col1);
                }
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTimKiemMaSach = new javax.swing.JTextField();
        txtTimKiemTenSach = new javax.swing.JTextField();
        txtTimKiemTacGia = new javax.swing.JTextField();
        txtTimKiemNhaXuatBan = new javax.swing.JTextField();
        txtTimKiemTheLoai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxTimKiemTinhTrang = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        btnCapNhatThemSach = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCapNhatSuaSach = new javax.swing.JButton();
        btnCapNhatXoaSach = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnTimKiemInRaFile = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTimKiemKetQua = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 650));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Owl-Book-64.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ SÁCH");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("@Author Nguyễn Hoàng Giang");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("MSSV: 20151094");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));

        jPanel10.setBackground(new java.awt.Color(51, 204, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Sách:"));

        jLabel2.setText("Mã Sách:");

        jLabel3.setText("Tên Sách:");

        jLabel4.setText("Tác Giả:");

        jLabel5.setText("Nhà Xuất Bản:");

        jLabel6.setText("Thể Loại:");

        jLabel12.setText("Tình Trạng:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiemMaSach)
                    .addComponent(txtTimKiemTenSach)
                    .addComponent(txtTimKiemTacGia)
                    .addComponent(txtTimKiemNhaXuatBan)
                    .addComponent(txtTimKiemTheLoai)
                    .addComponent(cbxTimKiemTinhTrang, 0, 183, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTimKiemMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTimKiemTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTimKiemTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(txtTimKiemNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtTimKiemTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbxTimKiemTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTimKiem.setBackground(new java.awt.Color(51, 204, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Search-16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnCapNhatThemSach.setBackground(new java.awt.Color(51, 204, 255));
        btnCapNhatThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Add Book-16.png"))); // NOI18N
        btnCapNhatThemSach.setText("Thêm Sách");
        btnCapNhatThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatThemSachActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Microsoft Excel-16.png"))); // NOI18N
        jButton1.setText("Thêm Nhiều Sách Từ File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCapNhatSuaSach.setBackground(new java.awt.Color(51, 204, 255));
        btnCapNhatSuaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Edit-16.png"))); // NOI18N
        btnCapNhatSuaSach.setText("Sửa Sách");
        btnCapNhatSuaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatSuaSachActionPerformed(evt);
            }
        });

        btnCapNhatXoaSach.setBackground(new java.awt.Color(51, 204, 255));
        btnCapNhatXoaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Add Book-16 (1).png"))); // NOI18N
        btnCapNhatXoaSach.setText("Xóa Sách");
        btnCapNhatXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatXoaSachActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Broom-16.png"))); // NOI18N
        jButton2.setText("Làm Sạch Ô Nhập Liệu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-select-all.png"))); // NOI18N
        jButton3.setText("Xem Toàn Bộ Sách");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnTimKiemInRaFile.setBackground(new java.awt.Color(51, 204, 255));
        btnTimKiemInRaFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Print-16a.png"))); // NOI18N
        btnTimKiemInRaFile.setText("In Ra File");
        btnTimKiemInRaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemInRaFileActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(51, 204, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết Quả:"));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBackground(new java.awt.Color(51, 204, 255));

        tblTimKiemKetQua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTimKiemKetQuaMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblTimKiemKetQua);

        jPanel11.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTimKiemInRaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCapNhatXoaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCapNhatSuaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCapNhatThemSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCapNhatThemSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCapNhatSuaSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCapNhatXoaSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiemInRaFile)
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maSach = txtTimKiemMaSach.getText();
        String tenSach = txtTimKiemTenSach.getText();
        String tacGia = txtTimKiemTacGia.getText();
        String nhaXuatBan = txtTimKiemNhaXuatBan.getText();
        String theLoai = txtTimKiemTheLoai.getText();
        if (maSach.equals("") && tenSach.equals("") && tacGia.equals("") && nhaXuatBan.equals("") && theLoai.equals("") && cbxTimKiemTinhTrang.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            return;
        } else {
            if (cbxTimKiemTinhTrang.getSelectedIndex() == -1) {
                String tinhTrang = "";
                ArrayList<Sach> ds = bllSach.timKiemSach("%" + maSach + "%", "%" + tenSach + "%", "%" + tacGia + "%", "%" + nhaXuatBan + "%", "%" + theLoai + "%", "%" + tinhTrang + "%");
                dtmTimKiemSach = addDuLieuChotblTimKiem(ds);
                tblTimKiemKetQua.setModel(dtmTimKiemSach);
            } else {
                String tinhTrang = cbxTimKiemTinhTrang.getSelectedItem().toString();
                ArrayList<Sach> ds = bllSach.timKiemSach("%" + maSach + "%", "%" + tenSach + "%", "%" + tacGia + "%", "%" + nhaXuatBan + "%", "%" + theLoai + "%", "%" + tinhTrang + "%");
                dtmTimKiemSach = addDuLieuChotblTimKiem(ds);
                tblTimKiemKetQua.setModel(dtmTimKiemSach);
            }
            btnLast = btnTimKiem;
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed
    
    private DefaultTableModel addDuLieuChotblTimKiem(ArrayList<Sach> ds) {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã Sách");
        dtm.addColumn("Tên Sách");
        dtm.addColumn("Tác Giả");
        dtm.addColumn("Nhà Xuất Bản");
        dtm.addColumn("Thể Loại");
        dtm.addColumn("Tình Trạng");
        for (Sach s : ds) {
            Vector<String> v = new Vector<>();
            v.add(s.getMaSach_20151094());
            v.add(s.getTenSach_20151094());
            v.add(s.getTacGia_20151094());
            v.add(s.getNhaXuatBan_20151094());
            v.add(s.getTheLoai_20151094());
            v.add(s.getTinhTrang_20151094());
            dtm.addRow(v);
        }
        return dtm;
    }
    
    private void btnCapNhatThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatThemSachActionPerformed
        // TODO add your handling code here:
        //Cách 1
        //        int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn thêm sách", "Hỏi", JOptionPane.YES_NO_OPTION);
        //        if (kt != JOptionPane.YES_OPTION) {
        //            return;
        //        }
        //        String maSach = txtCapNhatMaSach.getText();
        //        String tenSach = txtCapNhatTenSach.getText();
        //        String tacGia = txtCapNhatTacGia.getText();
        //        String nhaXuatBan = txtCapNhatNhaXuatBan.getText();
        //        String theLoai = txtCapNhatTheLoai.getText();
        //        if (tenSach.equals("") && tacGia.equals("") && nhaXuatBan.equals("") && theLoai.equals("")) {
        //            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
        //        } else {
        //            DataBaseQuery.insertIntoSach(con, maSach, tenSach, tacGia, nhaXuatBan, theLoai);
        //            dtmToanBoSach = DataBaseQuery.SelectFromSach(con);
        //            tblToanBoSach.setModel(dtmToanBoSach);
        //            if (txtTimKiemMaSach.getText().equals("") && txtTimKiemTenSach.getText().equals("") && txtTimKiemTacGia.getText().equals("") && txtTimKiemNhaXuatBan.getText().equals("") && txtTimKiemTheLoai.getText().equals("")) {
        //                tblCapNhatKetQua.setModel(dtmToanBoSach);
        //                resettxtCapNhat();
        //                return;
        //            } else {
        //                btnTimKiem.doClick();
        //                resettxtCapNhat();
        //            }
        //        }

        //Cách 2
        String maSach = txtTimKiemMaSach.getText();
        String tenSach = txtTimKiemTenSach.getText();
        String tacGia = txtTimKiemTacGia.getText();
        String nhaXuatBan = txtTimKiemNhaXuatBan.getText();
        String theLoai = txtTimKiemTheLoai.getText();
        String tinhTrang = "";
        if (cbxTimKiemTinhTrang.getSelectedIndex() != -1) {
            tinhTrang = cbxTimKiemTinhTrang.getSelectedItem().toString();
        }
        String kiemTra = KiemTraDuLieuNhapThoaMan.kiemTraDuLieuNhapCapNhatSach(maSach, tenSach, tacGia, nhaXuatBan, theLoai, tinhTrang);
        if (kiemTra.equals("Chưa nhập dữ liệu")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            return;
        }
        if (kiemTra.equalsIgnoreCase("Chưa nhập mã sách")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã sách");
            return;
        }
        if (kiemTra.equals("Chưa nhập tên sách")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập tên sách");
            return;
        }
        if (kiemTra.equals("Chưa nhập tác giả")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập tác giả");
            return;
        }
        if (kiemTra.equals("Chưa nhập nhà xuất bản")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập nhà xuất bản");
            return;
        }
        if (kiemTra.equals("Chưa nhập thể loại")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập thể loại");
            return;
        }
        if (kiemTra.equals("Chưa chọn tình trạng sách")) {
            JOptionPane.showMessageDialog(null, "Chưa chọn tình trạng sách");
            return;
        }
        if (kiemTra.equals("Dữ liệu thỏa mãn")) {
            int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn thêm sách", "Xác Nhận", JOptionPane.YES_NO_OPTION);
            if (kt != JOptionPane.YES_OPTION) {
                return;
            }
            if (bllSach.themSach(maSach, tenSach, tacGia, nhaXuatBan, theLoai, tinhTrang) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm Thành công");
                hienThiToanBoSachLenBangDanhSach();
                jButton2.doClick();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
            }
            
        }
    }//GEN-LAST:event_btnCapNhatThemSachActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        //        chooser.setFileFilter(new FileFilter() {
        //            @Override
        //            public boolean accept(File f) {
        //                return f.getAbsolutePath().endsWith(".xslx");
        //            }
        //
        //            @Override
        //            public String getDescription() {
        //                return ".xslx";
        //            }
        //        });
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            int soLuong = importFile.docDanhSachSachTuFileExcel(file.getAbsolutePath());
            if (soLuong > 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công " + soLuong + " sách");
                hienThiToanBoSachLenBangDanhSach();
                jButton2.doClick();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void hienThiToanBoSachLenBangDanhSach() {
        ArrayList<Sach> ds = bllSach.layToanBoSach();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã Sách");
        dtm.addColumn("Tên Sách");
        dtm.addColumn("Tác Giả");
        dtm.addColumn("Nhà Xuất Bản");
        dtm.addColumn("Thể Loại");
        dtm.addColumn("Tình Trạng");
        for (Sach s : ds) {
            Vector<String> v = new Vector<>();
            v.add(s.getMaSach_20151094());
            v.add(s.getTenSach_20151094());
            v.add(s.getTacGia_20151094());
            v.add(s.getNhaXuatBan_20151094());
            v.add(s.getTheLoai_20151094());
            v.add(s.getTinhTrang_20151094());
            dtm.addRow(v);
        }
        tblTimKiemKetQua.setModel(dtm);
    }
    
    private void btnCapNhatSuaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatSuaSachActionPerformed
        // TODO add your handling code here:
        //Cách 1
        //        int row = tblCapNhatKetQua.getSelectedRow();
        //        if (row < 0) {
        //            JOptionPane.showMessageDialog(null, "Chưa chọn dữ liệu cần sửa");
        //            return;
        //        }
        //        int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa sách không ?", "Hỏi", JOptionPane.YES_NO_OPTION);
        //        if (kt != JOptionPane.YES_OPTION) {
        //            return;
        //        }
        //        String maSach = tblCapNhatKetQua.getValueAt(row, 0) + "";
        //        String tenSach = txtCapNhatTenSach.getText();
        //        String tacGia = txtCapNhatTacGia.getText();
        //        String nhaXuatBan = txtCapNhatNhaXuatBan.getText();
        //        String theLoai = txtCapNhatTheLoai.getText();
        //        DataBaseQuery.suaSach(con, maSach, tenSach, tacGia, nhaXuatBan, theLoai);
        //        resettxtCapNhat();
        //        hienThiToanBoSachLenBangDanhSach();
        //        if (txtTimKiemMaSach.getText().equals("") && txtTimKiemTenSach.getText().equals("") && txtTimKiemTacGia.getText().equals("") && txtTimKiemNhaXuatBan.getText().equals("") && txtTimKiemTheLoai.getText().equals("")) {
        //            tblCapNhatKetQua.setModel(dtmToanBoSach);
        //        } else {
        //            btnTimKiem.doClick();
        //        }
        //Cách 2
        int row = tblTimKiemKetQua.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Chưa chọn dữ liệu cần sửa");
            return;
        }
        String maSach = txtTimKiemMaSach.getText();
        String tenSach = txtTimKiemTenSach.getText();
        String tacGia = txtTimKiemTacGia.getText();
        String nhaXuatBan = txtTimKiemNhaXuatBan.getText();
        String theLoai = txtTimKiemTheLoai.getText();
        String tinhTrang = cbxTimKiemTinhTrang.getSelectedIndex() != -1 ? cbxTimKiemTinhTrang.getSelectedItem().toString() : "";
        String kiemTra = KiemTraDuLieuNhapThoaMan.kiemTraDuLieuNhapCapNhatSach(maSach, tenSach, tacGia, nhaXuatBan, theLoai, tinhTrang);
        if (kiemTra.equals("Chưa nhập dữ liệu")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            return;
        }
        if (kiemTra.equalsIgnoreCase("Chưa nhập mã sách")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã sách");
            return;
        }
        if (kiemTra.equals("Chưa nhập tên sách")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập tên sách");
            return;
        }
        if (kiemTra.equals("Chưa nhập tác giả")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập tác giả");
            return;
        }
        if (kiemTra.equals("Chưa nhập nhà xuất bản")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập nhà xuất bản");
            return;
        }
        if (kiemTra.equals("Chưa nhập thể loại")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập thể loại");
            return;
        }
        if (kiemTra.equals("Chưa chọn tình trạng sách")) {
            JOptionPane.showMessageDialog(null, "Chưa chọn tình trạng sách");
            return;
        }
        if (kiemTra.equals("Dữ liệu thỏa mãn")) {
            int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (kt != JOptionPane.YES_OPTION) {
                return;
            }
            int kq = bllSach.suaSach(maSach, tenSach, tacGia, nhaXuatBan, theLoai, tinhTrang);
            if (kq <= 0) {
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
                return;
            }
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            jButton2.doClick();
            hienThiToanBoSachLenBangDanhSach();
        }
    }//GEN-LAST:event_btnCapNhatSuaSachActionPerformed

    private void btnCapNhatXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatXoaSachActionPerformed
        // TODO add your handling code here:
        //Chỉ xóa được 1
        //        int row = tblCapNhatKetQua.getSelectedRow();
        //        if (row < 0) {
        //            JOptionPane.showMessageDialog(null, "Chưa chọn dữ liệu cần xóa");
        //            return;
        //        }
        //        int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa sách", "Hỏi", JOptionPane.YES_NO_OPTION);
        //        if (kt != JOptionPane.YES_OPTION) {
        //            return;
        //        }
        //        String maSach = tblCapNhatKetQua.getValueAt(row, 0) + "";
        //        DataBaseQuery.deleteSach(con, maSach);
        //        resettxtCapNhat();
        //        hienThiToanBoSachLenBangDanhSach();
        //        if (txtTimKiemMaSach.getText().equals("") && txtTimKiemTenSach.getText().equals("") && txtTimKiemTacGia.getText().equals("") && txtTimKiemNhaXuatBan.getText().equals("") && txtTimKiemTheLoai.getText().equals("")) {
        //            tblCapNhatKetQua.setModel(dtmToanBoSach);
        //        } else {
        //            btnTimKiem.doClick();
        //        }
        //Xóa được nhiều
        int[] row = tblTimKiemKetQua.getSelectedRows();
        if (row.length > 0) {
            int soLuong = 0;
            int kt = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa sách", "Hỏi", JOptionPane.YES_NO_OPTION);
            if (kt != JOptionPane.YES_OPTION) {
                return;
            }
            for (int r : row) {
                Sach sach = new Sach();
                sach.setMaSach_20151094(tblTimKiemKetQua.getValueAt(r, 0) + "");
                soLuong += bllSach.xoaSach(sach);
            }
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
                return;
            }
            JOptionPane.showMessageDialog(null, "Xóa thành công " + soLuong + "/" + row.length + " sách");
            jButton2.doClick();
            hienThiToanBoSachLenBangDanhSach();
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn dữ liệu cần xóa");
            return;
        }
    }//GEN-LAST:event_btnCapNhatXoaSachActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtTimKiemMaSach.setText("");
        txtTimKiemTenSach.setText("");
        txtTimKiemTacGia.setText("");
        txtTimKiemNhaXuatBan.setText("");
        txtTimKiemTheLoai.setText("");
        cbxTimKiemTinhTrang.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hienThiToanBoSachLenBangDanhSach();
        btnLast = jButton3;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnTimKiemInRaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemInRaFileActionPerformed
        // TODO add your handling code here:
        if (btnLast == btnTimKiem || btnLast == jButton3) {
            if (btnLast == btnTimKiem) {
                String maSach = txtTimKiemMaSach.getText();
                String tenSach = txtTimKiemTenSach.getText();
                String tacGia = txtTimKiemTacGia.getText();
                String nhaXuatBan = txtTimKiemNhaXuatBan.getText();
                String theLoai = txtTimKiemTheLoai.getText();
                String tinhTrang = "";
                if (cbxTimKiemTinhTrang.getSelectedIndex() != -1) {
                    tinhTrang = cbxTimKiemTinhTrang.getSelectedItem() + "";
                }
                String regex = "\\s*";
                if (maSach.matches(regex) && tenSach.matches(regex) && tacGia.matches(regex) && nhaXuatBan.matches(regex) && theLoai.matches(regex) && tinhTrang.matches(regex)) {
                    JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu để tìm kiếm.");
                    return;
                }
                JOptionPane.showMessageDialog(null, "<html><p>Đang chuẩn bị in kết quả.</p>"
                        + "<p>Vui lòng đợi trong giây lát.</p></html>");
                printSach.printKetQuaTimKiemSach("%" + maSach + "%", "%" + tenSach + "%", "%" + tacGia + "%", "%" + nhaXuatBan + "%", "%" + theLoai + "%", "%" + tinhTrang + "%");
            } else {
                JOptionPane.showMessageDialog(null, "<html><p>Đang chuẩn bị in kết quả.</p>"
                        + "<p>Vui lòng đợi trong giây lát.</p></html>");
                printSach.printToanBoSach();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hãy tìm kiếm trước.");
        }
    }//GEN-LAST:event_btnTimKiemInRaFileActionPerformed

    private void tblTimKiemKetQuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTimKiemKetQuaMousePressed
        // TODO add your handling code here:
        int row = tblTimKiemKetQua.getSelectedRow();
        txtTimKiemMaSach.setText((tblTimKiemKetQua.getValueAt(row, 0) + "").trim());
        txtTimKiemTenSach.setText(tblTimKiemKetQua.getValueAt(row, 1) + "");
        txtTimKiemNhaXuatBan.setText(tblTimKiemKetQua.getValueAt(row, 3) + "");
        txtTimKiemTacGia.setText(tblTimKiemKetQua.getValueAt(row, 2) + "");
        txtTimKiemTheLoai.setText(tblTimKiemKetQua.getValueAt(row, 4) + "");
        String tinhTrang = tblTimKiemKetQua.getValueAt(row, 5) + "";
        tinhTrang.trim();
        if (tinhTrang.equalsIgnoreCase("Còn sách")) {
            cbxTimKiemTinhTrang.setSelectedIndex(0);
        } else if (tinhTrang.equalsIgnoreCase("Đã cho mượn")) {
            cbxTimKiemTinhTrang.setSelectedIndex(1);
        } else if (tinhTrang.equalsIgnoreCase("Không tồn tại")) {
            cbxTimKiemTinhTrang.setSelectedIndex(2);
        }
    }//GEN-LAST:event_tblTimKiemKetQuaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatSuaSach;
    private javax.swing.JButton btnCapNhatThemSach;
    private javax.swing.JButton btnCapNhatXoaSach;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiemInRaFile;
    private javax.swing.JComboBox<String> cbxTimKiemTinhTrang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblTimKiemKetQua;
    private javax.swing.JTextField txtTimKiemMaSach;
    private javax.swing.JTextField txtTimKiemNhaXuatBan;
    private javax.swing.JTextField txtTimKiemTacGia;
    private javax.swing.JTextField txtTimKiemTenSach;
    private javax.swing.JTextField txtTimKiemTheLoai;
    // End of variables declaration//GEN-END:variables
}
